export enum Diseases {
  COVID19 = "COVID-19",
  Influenza = "Influenza",
  Pneumonia = "Pneumonia",
  Tuberculosis = "Tuberculosis",
  Malaria = "Malaria",
  HIV = "HIV/AIDS",
  Hepatitis = "Hepatitis",
  Dengue = "Dengue",
  Ebola = "Ebola",
  Zika = "Zika",
  Cholera = "Cholera",
  Typhoid = "Typhoid",
  Measles = "Measles",
  Mumps = "Mumps",
  Rubella = "Rubella",
  Polio = "Polio",
  Pertussis = "Pertussis",
  Tetanus = "Tetanus",
  YellowFever = "Yellow Fever",
  Rabies = "Rabies",
  BubonicPlague = "Bubonic Plague",
  Smallpox = "Smallpox",
  Chickenpox = "Chickenpox",
  SARS = "SARS",
  MERS = "MERS",
  H1N1 = "H1N1",
  H5N1 = "H5N1",
  H7N9 = "H7N9",
  H1N2 = "H1N2",
  H3N2 = "H3N2",
  H9N2 = "H9N2",
  H7N2 = "H7N2",
  H10N7 = "H10N7",
  H7N7 = "H7N7",
  H7N3 = "H7N3",
  H5N2 = "H5N2",
  H9N1 = "H9N1",
  H5N6 = "H5N6",
  H7N8 = "H7N8",
  H5N8 = "H5N8",
  H5N3 = "H5N3",
  H7N1 = "H7N1",
  H10N8 = "H10N8",
  H10N5 = "H10N5",
  H10N4 = "H10N4",
  H10N3 = "H10N3",
  H10N2 = "H10N2",
  H10N1 = "H10N1",
  H10N9 = "H10N9",
  H10N6 = "H10N6",
}

export enum MedicalSpecialties {
  AllergyAndImmunology = "Allergy and Immunology",
  Anesthesiology = "Anesthesiology",
  Cardiology = "Cardiology",
  Dermatology = "Dermatology",
  EmergencyMedicine = "Emergency Medicine",
  Endocrinology = "Endocrinology",
  FamilyMedicine = "Family Medicine",
  Gastroenterology = "Gastroenterology",
  Geriatrics = "Geriatrics",
  Hematology = "Hematology",
  InfectiousDisease = "Infectious Disease",
  InternalMedicine = "Internal Medicine",
  MedicalGenetics = "Medical Genetics",
  Nephrology = "Nephrology",
  Neurology = "Neurology",
  ObstetricsAndGynecology = "Obstetrics and Gynecology",
  Oncology = "Oncology",
  Ophthalmology = "Ophthalmology",
  Orthopedics = "Orthopedics",
  Otolaryngology = "Otolaryngology",
  Pathology = "Pathology",
  Pediatrics = "Pediatrics",
  PhysicalMedicineAndRehabilitation = "Physical Medicine and Rehabilitation",
  Psychiatry = "Psychiatry",
  Pulmonology = "Pulmonology",
  Radiology = "Radiology",
  Rheumatology = "Rheumatology",
  SportsMedicine = "Sports Medicine",
  Surgery = "Surgery",
  Urology = "Urology",
  Other = "Other",
}

export enum BloodTypes {
  APositive = "A+",
  ANegative = "A-",
  BPositive = "B+",
  BNegative = "B-",
  ABPositive = "AB+",
  ABNegative = "AB-",
  OPositive = "O+",
  ONegative = "O-",
}

export enum UnitsOfMeasurementMedication {
  Milligram = "mg",
  Gram = "g",
  Kilogram = "kg",
  Microgram = "mcg",
  Liter = "L",
  Milliliter = "mL",
  Teaspoon = "tsp",
  Tablespoon = "Tbsp",
  FluidOunce = "fl oz",
  Pint = "pt",
  Quart = "qt",
  Gallon = "gal",
  Milliequivalent = "mEq",
  InternationalUnit = "IU",
  Drop = "drop",
  Spray = "spray",
  Inhalation = "inhalation",
  Suppository = "suppository",
  Lozenge = "lozenge",
  Patch = "patch",
  Ointment = "ointment",
  Cream = "cream",
  Lotion = "lotion",
  Solution = "solution",
  Suspension = "suspension",
  Syrup = "syrup",
  Tablet = "tablet",
  Capsule = "capsule",
  Unit = "unit",
  Package = "package",
}

export enum UnitsOfMeasurementVitalSigns {
  MillimeterOfMercury = "mmHg",
  BeatsPerMinute = "bpm",
  RespirationsPerMinute = "rpm",
  DegreesCelsius = "°C",
  DegreesFahrenheit = "°F",
  Percent = "%",
}

export enum MedicationForms {
  Tablet = "Tablet",
  Capsule = "Capsule",
  Syrup = "Syrup",
  Injection = "Injection",
  Inhaler = "Inhaler",
  Ointment = "Ointment",
  Cream = "Cream",
  Lotion = "Lotion",
  Solution = "Solution",
  Suspension = "Suspension",
  Suppository = "Suppository",
  Lozenge = "Lozenge",
  Patch = "Patch",
}
