// Science enums

export enum Physics {
    Mechanics = "Mechanics",
    Thermodynamics = "Thermodynamics",
    Electromagnetism = "Electromagnetism",
    Optics = "Optics",
    QuantumMechanics = "Quantum Mechanics",
    Relativity = "Relativity",
    NuclearPhysics = "Nuclear Physics",
    ParticlePhysics = "Particle Physics",
    Astrophysics = "Astrophysics",
    Other = "Other"
}

export enum Chemistry {
    Organic = "Organic",
    Inorganic = "Inorganic",
    Physical = "Physical",
    Analytical = "Analytical",
    Biochemistry = "Biochemistry",
    Other = "Other"
}

export enum Biology {
    Botany = "Botany",
    Zoology = "Zoology",
    Genetics = "Genetics",
    Ecology = "Ecology",
    Microbiology = "Microbiology",
    Other = "Other"
}

export enum Geology {
    Geophysics = "Geophysics",
    Geochemistry = "Geochemistry",
    Geochronology = "Geochronology",
    Geomorphology = "Geomorphology",
    Glaciology = "Glaciology",
    Hydrology = "Hydrology",
    Mineralogy = "Mineralogy",
    Petrology = "Petrology",
    Sedimentology = "Sedimentology",
    Seismology = "Seismology",
    SoilScience = "Soil Science",
    Stratigraphy = "Stratigraphy",
    Tectonics = "Tectonics",
    Volcanology = "Volcanology",
    Other = "Other"
}

export enum Astronomy {
    SolarSystem = "Solar System",
    Stars = "Stars",
    Galaxies = "Galaxies",
    Cosmology = "Cosmology",
    Other = "Other"
}

export enum Mathematics {
    Arithmetic = "Arithmetic",
    Algebra = "Algebra",
    Geometry = "Geometry",
    Trigonometry = "Trigonometry",
    Calculus = "Calculus",
    Statistics = "Statistics",
    Probability = "Probability",
    NumberTheory = "Number Theory",
    Combinatorics = "Combinatorics",
    GraphTheory = "Graph Theory",
    SetTheory = "Set Theory",
    Topology = "Topology",
    Other = "Other"
}

export enum ComputerScience {
    Algorithms = "Algorithms",
    DataStructures = "Data Structures",
    Databases = "Databases",
    Networking = "Networking",
    CyberSecurity = "Cyber Security",
    Cryptography = "Cryptography",
    MachineLearning = "Machine Learning",
    ArtificialIntelligence = "Artificial Intelligence",
    ComputerGraphics = "Computer Graphics",
    HumanComputerInteraction = "Human-Computer Interaction",
    OperatingSystems = "Operating Systems",
    SoftwareEngineering = "Software Engineering",
    WebDevelopment = "Web Development",
    Other = "Other"
}

export enum Medicine {
    Anatomy = "Anatomy",
    Physiology = "Physiology",
    Immunology = "Immunology",
    Pathology = "Pathology",
    Pharmacology = "Pharmacology",
    Epidemiology = "Epidemiology",
    Other = "Other"
}

export enum OtherScience {
    Psychology = "Psychology",
    Sociology = "Sociology",
    Economics = "Economics",
    PoliticalScience = "Political Science",
    Linguistics = "Linguistics",
    Other = "Other"
}

export enum ChemicalElement {
    H = "Hydrogen",
    He = "Helium",
    Li = "Lithium",
    Be = "Beryllium",
    B = "Boron",
    C = "Carbon",
    N = "Nitrogen",
    O = "Oxygen",
    F = "Fluorine",
    Ne = "Neon",
    Na = "Sodium",
    Mg = "Magnesium",
    Al = "Aluminum",
    Si = "Silicon",
    P = "Phosphorus",
    S = "Sulfur",
    Cl = "Chlorine",
    Ar = "Argon",
    K = "Potassium",
    Ca = "Calcium",
    Sc = "Scandium",
    Ti = "Titanium",
    V = "Vanadium",
    Cr = "Chromium",
    Mn = "Manganese",
    Fe = "Iron",
    Co = "Cobalt",
    Ni = "Nickel",
    Cu = "Copper",
    Zn = "Zinc",
    Ga = "Gallium",
    Ge = "Germanium",
    As = "Arsenic",
    Se = "Selenium",
    Br = "Bromine",
    Kr = "Krypton",
    Rb = "Rubidium",
    Sr = "Strontium",
    Y = "Yttrium",
    Zr = "Zirconium",
    Nb = "Niobium",
    Mo = "Molybdenum",
    Tc = "Technetium",
    Ru = "Ruthenium",
    Rh = "Rhodium",
    Pd = "Palladium",
    Ag = "Silver",
    Cd = "Cadmium",
    In = "Indium",
    Sn = "Tin",
    Sb = "Antimony",
    Te = "Tellurium",
    I = "Iodine",
    Xe = "Xenon",
    Cs = "Cesium",
    Ba = "Barium",
    La = "Lanthanum",
    Ce = "Cerium",
    Pr = "Praseodymium",
    Nd = "Neodymium",
    Pm = "Promethium",
    Sm = "Samarium",
    Eu = "Europium",
    Gd = "Gadolinium",
    Tb = "Terbium",
    Dy = "Dysprosium",
    Ho = "Holmium",
    Er = "Erbium",
    Tm = "Thulium",
    Yb = "Ytterbium",
    Lu = "Lutetium",
    Hf = "Hafnium",
    Ta = "Tantalum",
    W = "Tungsten",
    Re = "Rhenium",
    Os = "Osmium",
    Ir = "Iridium",
    Pt = "Platinum",
    Au = "Gold",
    Hg = "Mercury",
    Tl = "Thallium",
    Pb = "Lead",
    Bi = "Bismuth",
    Po = "Polonium",
    At = "Astatine",
    Rn = "Radon",
    Fr = "Francium",
    Ra = "Radium",
    Ac = "Actinium",
    Th = "Thorium",
    Pa = "Protactinium",
    U = "Uranium",
    Np = "Neptunium",
    Pu = "Plutonium",
    Am = "Americium",
    Cm = "Curium",
    Bk = "Berkelium",
    Cf = "Californium",
    Es = "Einsteinium",
    Fm = "Fermium",
    Md = "Mendelevium",
    No = "Nobelium",
    Lr = "Lawrencium",
    Rf = "Rutherfordium",
    Db = "Dubnium",
    Sg = "Seaborgium",
    Bh = "Bohrium",
    Hs = "Hassium",
    Mt = "Meitnerium",
    Ds = "Darmstadtium",
    Rg = "Roentgenium",
    Cn = "Copernicium",
    Nh = "Nihonium",
    Fl = "Flerovium",
    Mc = "Moscovium",
    Lv = "Livermorium",
    Ts = "Tennessine",
    Og = "Oganesson"
}

export enum ChemicalCompounds {
    Water = "H2O",
    CarbonDioxide = "CO2",
    SodiumChloride = "NaCl",
    SulfuricAcid = "H2SO4",
    Glucose = "C6H12O6",
    Ammonia = "NH3",
    Methane = "CH4",
    Ethanol = "C2H5OH",
    Oxygen = "O2",
    Nitrogen = "N2",
    AceticAcid = "CH3COOH",
    CalciumCarbonate = "CaCO3",
    SodiumHydroxide = "NaOH",
    MagnesiumSulfate = "MgSO4",
    HydrochloricAcid = "HCl",
    PotassiumPermanganate = "KMnO4",
    Benzene = "C6H6",
    SodiumBicarbonate = "NaHCO3",
    NitricAcid = "HNO3",
    PhosphoricAcid = "H3PO4",
    Acetone = "C3H6O",
    AluminiumOxide = "Al2O3",
    AmmoniumNitrate = "NH4NO3",
    CalciumChloride = "CaCl2",
    CarbonMonoxide = "CO",
    CitricAcid = "C6H8O7",
    DiethylEther = "C4H10O",
    EthyleneGlycol = "C2H6O2",
    Formaldehyde = "CH2O",
    Glycerol = "C3H8O3",
    LSD = "C20H25N3O"
}

export enum Planets {
    Mercury = "Mercury",
    Venus = "Venus",
    Earth = "Earth",
    Mars = "Mars",
    Jupiter = "Jupiter",
    Saturn = "Saturn",
    Uranus = "Uranus",
    Neptune = "Neptune"
}

export enum Moons {
    Moon = "Moon",
    Phobos = "Phobos",
    Deimos = "Deimos",
    Io = "Io",
    Europa = "Europa",
    Ganymede = "Ganymede",
    Callisto = "Callisto",
    Mimas = "Mimas",
    Enceladus = "Enceladus",
    Tethys = "Tethys",
    Dione = "Dione",
    Rhea = "Rhea",
    Titan = "Titan",
    Iapetus = "Iapetus",
    Miranda = "Miranda",
    Ariel = "Ariel",
    Umbriel = "Umbriel",
    Titania = "Titania",
    Oberon = "Oberon",
    Triton = "Triton",
    Charon = "Charon"
}

export enum Plantoids {
    Ceres = "Ceres",
    Pluto = "Pluto",
    Haumea = "Haumea",
    Makemake = "Makemake",
    Eris = "Eris"
}

export enum AstronomicalObjects {
    Star = "Star",
    Planet = "Planet",
    DwarfPlanet = "Dwarf Planet",
    Satellite = "Satellite",
    Comet = "Comet",
    Asteroid = "Asteroid",
    Meteoroid = "Meteoroid",
    Galaxy = "Galaxy",
    Nebula = "Nebula",
    BlackHole = "Black Hole",
    Pulsar = "Pulsar",
    Quasar = "Quasar",
    GalaxyCluster = "Galaxy Cluster",
    Supercluster = "Supercluster",
    NebulaCluster = "Nebula Cluster",
    StarCluster = "Star Cluster",
    Exoplanet = "Exoplanet",
    BrownDwarf = "Brown Dwarf",
    WhiteDwarf = "White Dwarf",
    RedGiant = "Red Giant",
    Supernova = "Supernova",
    NeutronStar = "Neutron Star",
    SolarSystem = "Solar System",
    Universe = "Universe",
    // Specific notable objects can also be added as needed
    MilkyWay = "Milky Way",
    AndromedaGalaxy = "Andromeda Galaxy",
    OrionNebula = "Orion Nebula"
}
